version: '3.3'

services:
  db:
    image: mariadb:10.6.4-focal
    container_name: wordpress_site_db
    ports:
      - "3306:3306"
    volumes:
      - ./.db_data/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    container_name: wordpress_site_wordpress
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    working_dir: /var/www/html
    volumes:
      - ./wordpress:/var/www/html/wp-content/themes/wordpress
      - ./plugins:/var/www/html/wp-content/plugins
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress